version: '3.9'

services:
  postgres_db:
    image: postgres:16.0-alpine
    container_name: "postgres_db"
    environment:
      POSTGRES_DB: "clients"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5632:5432"
    volumes:
      - ./scripts/postgres_db:/scripts
      #- postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

  postgres_db1:
    image: postgres:16.0-alpine
    container_name: "postgres_db1"
    environment:
      POSTGRES_DB: "clients"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5633:5432"
    volumes:
      - ./scripts/postgres_db1/:/scripts/
      #- postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

  postgres_db2:
    image: postgres:16.0-alpine
    container_name: "postgres_db2"
    environment:
      POSTGRES_DB: "clients"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5634:5432"
    volumes:
      - ./scripts/postgres_db2/:/scripts/
      #- postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
    driver: local